include: "olivenucmer.snakefile"
include: "apulnucmer.snakefile"
include: "orthofinder.snakefile"
include: "busco.snakefile"
include: "blast.snakefile"
include: 'sourmashlca.snakefile'

rule all:
    input:
        dynamic("outputs/Oe6/blast/tab/{contig_names}.tab"),
        #dynamic("outputs/sylvestris/blast/tab/{contig_names_sylv}.tab"),
        'outputs/sourmash_lca/Oe6.scaffolds-k31.fa.lca.txt',
        'outputs/sourmash_lca/Olea_europaea_1kb_scaffolds-k31.lca.txt',
        'outputs/olive_genomes_nucmer/sylvester_santander_nucmer_filter_coords.txt',
        'outputs/aur-pul-nucmer/Oe6-APvarSan_filter_coords.txt',
        'outputs/aur-pul-nucmer/Oe6-APvarEx_filter_coords.txt',
        'outputs/busco/run_wild_olive_busco',
        expand('inputs/peptides/Results_{date}/Orthogroups.csv', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/Orthogroups.txt', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/Orthogroups_UnassignedGenes.csv', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/Orthogroups.GeneCount.csv', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/Statistics_Overall.csv', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/Statistics_PerSpecies.csv', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/WorkingDirectory/Blast0_0.txt', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/WorkingDirectory/clusters_OrthoFinder_v1.1.10_I1.5.txt_id_pairs.txt', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/WorkingDirectory/SequenceIDs.txt', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/WorkingDirectory/SpeciesIDs.txt', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/WorkingDirectory/clusters_OrthoFinder_v1.1.10_I1.5.txt', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/WorkingDirectory/OrthoFinder_v1.1.10_graph.txt', date = ['Jan21']),
        expand('inputs/peptides/Results_{date}/WorkingDirectory/Species0.fa', date = ['Jan21'])